"""add analysis reports table

Revision ID: af3efe0e8f8c
Revises: 5da68a6f12fc
Create Date: 2026-07-04 14:25:31.974359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3efe0e8f8c'
down_revision: Union[str, Sequence[str], None] = '5da68a6f12fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('resume_skills', sa.JSON(), nullable=False),
    sa.Column('jd_skills', sa.JSON(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('extra_skills', sa.JSON(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=False),
    sa.Column('skill_match_score', sa.Float(), nullable=False),
    sa.Column('keyword_coverage_score', sa.Float(), nullable=False),
    sa.Column('resume_quality_score', sa.Float(), nullable=False),
    sa.Column('report_summary', sa.Text(), nullable=True),
    sa.Column('role_readiness', sa.String(length=100), nullable=True),
    sa.Column('improvement_plan', sa.JSON(), nullable=False),
    sa.Column('interview_focus', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('evidence_snippets', sa.JSON(), nullable=False),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('graph_version', sa.String(length=50), nullable=False),
    sa.Column('workflow_trace', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_id'), 'analysis_reports', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_resume_id'), 'analysis_reports', ['resume_id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_user_id'), 'analysis_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_reports_user_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_resume_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
